global using System.ComponentModel.DataAnnotations.Schema;
global using MohamedSprint1V2.DAL.EntityClasses;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using System.ComponentModel;
global using MohamedSprint1V2.DAL.Entity;
global using Microsoft.EntityFrameworkCore;
global using MohamedSprint1V2.DAL.Repo.Abstraction;
global using System.Linq.Expressions;
global using MohamedSprint1V2.DAL.Database;
// في: MohamedSprint1V2.DAL/Global/global.cs
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using System.ComponentModel;
global using MohamedSprint1V2.DAL.Entity;
global using Microsoft.EntityFrameworkCore;
global using MohamedSprint1V2.DAL.Repo.Abstraction;
global using System.Linq.Expressions;
global using MohamedSprint1V2.DAL.Database;
global using MohamedSprint1V2.DAL.EntityClasses;
global using Microsoft.AspNetCore.Identity;  // ✅ ADD THIS